baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Dino.AI'
theme = 'dinoai'

[markup]
  [markup.highlight]
    lineNos = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 5
    startLevel = 2

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
