baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'DinoAI'

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.highlight]
      codeFences = false
      lineNos = true
